# Generated by Django 5.2.11 on 2026-05-15 13:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_id', models.CharField(editable=False, max_length=15, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid Kenyan number (e.g., 0712345678, 254712345678, or +254712345678)', regex='^(?:\\+254|254|0)((?:[7][0-24-9]|[1][0-1])\\d{7})$')])),
                ('location', models.CharField(blank=True, max_length=100)),
                ('milling_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('milking_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('joined_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FarmerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference', models.CharField(help_text='M-Pesa Ref', max_length=50)),
                ('category', models.CharField(choices=[('MILK', 'Milk'), ('MAIZE', 'Maize')], default='MILK', max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaizeIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intake_no', models.CharField(editable=False, max_length=20, unique=True)),
                ('sacks_delivered', models.PositiveIntegerField()),
                ('price_per_sack', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_credit', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaizeStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sacks', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MilkCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_no', models.CharField(editable=False, max_length=20, unique=True)),
                ('litres', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buying_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Milk Collection',
                'verbose_name_plural': 'Milk Collections',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MillingBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(editable=False, max_length=20, unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sacks_pulled_from_store', models.PositiveIntegerField()),
                ('one_kg_flour_bales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('two_kg_flour_bales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('maize_germ_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('maize_bran_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('checkout_request_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('transaction_no', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('transaction_type', models.CharField(choices=[('PAYMENT', 'Customer Payment'), ('PAYOUT', 'Farmer Payout')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(choices=[('FLOUR1', 'Unga Bale 1 kg'), ('FLOUR2', 'Unga Bale 2 kg'), ('GERM', 'Maize Germ'), ('BRAN', 'Maize Bran'), ('MILK', 'Fresh Milk')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_revenue', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('payment_status', models.CharField(choices=[('PAID', 'Paid / Cash'), ('CREDIT', 'On Credit / Pending')], default='PAID', max_length=10)),
                ('customer_name', models.CharField(blank=True, help_text='Who bought on credit?', max_length=100, null=True)),
                ('sold_at', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('MPESA', 'M-Pesa'), ('CREDIT', 'Credit')], default='CASH', max_length=10)),
                ('mpesa_checkout_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('FLOUR', 'Unga Bale'), ('GERM', 'Maize Germ'), ('BRAN', 'Maize Bran'), ('MILK', 'Fresh Milk')], max_length=10, unique=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
