# Generated by Django 5.2.11 on 2026-05-15 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='farmerpayment',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.farmer'),
        ),
        migrations.AddField(
            model_name='maizeintake',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maize_deliveries', to='Home.farmer'),
        ),
        migrations.AddField(
            model_name='milkcollection',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_collections', to='Home.farmer'),
        ),
        migrations.AddField(
            model_name='farmerpayment',
            name='mpesa_payout',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.mpesatransaction'),
        ),
        migrations.AddField(
            model_name='productsale',
            name='mpesa_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.mpesatransaction'),
        ),
    ]
