# Generated by Django 5.2.11 on 2026-06-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsale',
            name='receipt_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
