"""
Django settings for MMS project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

import dj_database_url
TIME_ZONE = 'Africa/Nairobi'
USE_TZ = True

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# M-Pesa API Configuration (Daraja Sandbox)
MPESA_CONSUMER_KEY = 'zGwNsbORIOzKwqA2P3sgr0ArDopPQotM1iyyRhjGmdGj7n4T'
MPESA_CONSUMER_SECRET = 'EMjOYhpEjagIsSvwa5Yucq68e7hGL9yAvWRvZqqLJQ9uS1E5a0ufLD73vkV8ALtg'
MPESA_PASSKEY = 'bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919'
MPESA_CALLBACK_URL = 'https://your-domain.com/mpesa/callback/'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-o9^w15653c9!2(^$l1crynd+1_z2e5yno=%_ku!^@gdee0!%ve'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG =True
# settings.py

# 1. Add the ngrok domain to ALLOWED_HOSTS
#ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'scallop-epic-sandlot.ngrok-free.dev' ]
ALLOWED_HOSTS = ['*']
# 2. Update the Callback URL for M-Pesa
MPESA_CALLBACK_URL = 'https://scallop-epic-sandlot.ngrok-free.dev/mpesa/callback/'
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    "Home",
    'Users',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'MMS.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'MMS.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


DATABASES = {
    'default': dj_database_url.config(
        default='postgresql://mms_jqlu_user:Th0vrQQiymboQCWUVBxYML3Qwh9ohG5J@dpg-d8sfbkb7uimc738aibgg-a.oregon-postgres.render.com/mms_jqlu',
        conn_max_age=600,
        ssl_require=True
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# The directory where collectstatic will gather files for production
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATIC_URL = '/static/'

# Enable WhiteNoise compression and caching support
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'Users.CustomUser'
AUTHENTICATION_BACKENDS = [
    'Users.backends.PhoneOrEmailBackend', # Path to the class we just created
    'django.contrib.auth.backends.ModelBackend', # Keep default as fallback
]
LOGIN_URL = '/login/'  # Cha
LOGIN_REDIRECT_URL = 'home' 
# 1. Session age in seconds (5 min
SESSION_COOKIE_AGE = 3600
# 2. Logout the user when the brow
SESSION_EXPIRE_AT_BROWSER_CLOSE = True


# 3. Save the session on every req
SESSION_SAVE_EVERY_REQUEST = True